[package]
name = "shadowprism-core"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
axum = { version = "0.8.8", features = ["macros"] }
reqwest = "0.13.1"
rusqlite = "0.38.0"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["auth", "util"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
